from typing import Protocol


class HealthChecker(Protocol):
    async def check_qdrant(self) -> bool: ...

    async def check_ollama(self) -> bool: ...

    async def check_docs(self) -> bool: ...

    async def check_rag_canary(self) -> bool: ...
